version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./mvnw clean install -DskipTests
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: ./mvnw test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
